mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

admin.sites.AdminSite.site_header = "Home Main Branch"
admin.sites.AdminSite.site_title = "HMB Admin Portal"
admin.sites.AdminSite.index_title = "Welcome to HMB Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('gamepage.urls')),
    path('',include('accounts.urls')),

]

mysite/homepage/forms.py
from django import forms
from django.contrib.auth import authenticate,get_user_model
from django.contrib.auth.models import User
user=get_user_model()
class UserLoginForm(forms.Form):
    username=forms.CharField(label='Username',required = True,widget=forms.TextInput(attrs={"placeholder":"Username"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}), label='Password',required = True)
    check = forms.BooleanField(label='Remember me',required=False)

    class Meta:
        model=user
        fields=[
          
            'username',
            'password',
            
        ]

    def post(self, request, *args, **kwargs):
        form = UserLoginForm(request.POST)
        for field in form:
            print("Field Error:", field.name,  field.errors)
    def clean(self,*args,**kwargs):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')
        check = self.cleaned_data.get('check')
    

        if username and password:
            user=authenticate(username = username,password=password)

            if not user:
                raise forms.ValidationError('User Does Not Exist')
            
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')
        
        return super(UserLoginForm, self).clean(*args,**kwargs)



class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder":"Email"}), label='email',required = True)

    newuser=forms.CharField(label='Username',required = True,widget=forms.TextInput(attrs={"placeholder":"Username"}))
    
    password1=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}), label='Password',required = True)
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}), label='Confirm Password',required = True)

    class Meta:
        model=user
        fields=[
            'email',
            'newuser',
            'password1',
            'password2',
        ]
    def post(self, request, *args, **kwargs):
        form = UserRegisterForm(request.POST)
        for field in form:
            print("Field Error:", field.name,  field.errors)
    def clean(self,*args,**kwargs):
        email = self.cleaned_data.get("email")
        newuser = self.cleaned_data.get('newuser')
        password1=self.cleaned_data.get('password1')
        password2=self.cleaned_data.get('password2')
        if User.objects.filter(username=newuser).exists():
            raise forms.ValidationError("Username is not unique")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email is not unique")
        if password1!=password2:
            raise forms.ValidationError("Passwords Don't Match")

        # username_qs=user.objects.filter(username = username)
        # if username_qs.exists():
        #     raise forms.ValidationError("Username Already In Use")

        return super(UserRegisterForm, self).clean(*args,**kwargs)

mysite/templates/baseWOnav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>

    <!-- Unicons -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />

    <!-- user custom -->
    
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">

    {% block header %}


    {% endblock header %}


    


    <title>Sample</title>
</head>
<body>

    {% block content %}


    {% endblock content %}

    

</body>
<style>
  body{
    background-color: black;
  }
  
</style>
</html>

mysite/templates/form.html
{% load socialaccount %}
<section class="home">
  <div class="form_container">
    <i class="uil uil-times form_close"></i>

    <!-- Login From -->
    <div class="form login_form">
      <form action='.' method="POST">
        {% csrf_token %}
        <h2>Login</h2>

        <div class="input_box">

          {{form1.username}}
          <i class="uil uil-envelope-alt email"></i>
        </div>
        <div class="input_box">

          {{form1.password}}
          <i class="uil uil-lock password"></i>
          <i class="uil uil-eye-slash pw_hide"></i>
        </div>

        <div class="option_field">
          <span class="checkbox">

            {{form1.check}}
            <label for="id_check">Remember me</label>

          </span>
          <a href="/recoverpassword" class="forgot_pw">Forgot password?</a>
        </div>
        {% if retryLogin %}
        <p style="color:rgb(219, 28, 14);text-align: center; margin-bottom: 0px;">
          {% for field in form1 %}
          {% for err in field.errors %}
          {{err}}
          {%endfor %}
          {%endfor %}
          {% for error in form1.non_field_errors %}
          {{error}}
          {%endfor%}
        </p>
        {% endif %}

        <button class="button">Login Now</button>
        <!-- google auth button -->
       
        <div class="google_signup">Login With Google
          <a href="{% provider_login_url 'google'%}?next=/">
            <i class="fab fa-google google-icon"></i>
          </a>
        </div>
      
        
        

        <div class="login_signup">Don't have an account? <a href="#" id="signup">Signup</a></div>
      </form>


    </div>

    <!-- Signup From -->

    <div class="form signup_form">
      <form action='.' method="post">
        {% csrf_token %}
        <h2>Signup</h2>
        <!-- <input type="hidden" value="signup" name="formType" /> -->
        <div class="input_box">
          <!-- <input type="email" placeholder="Enter your email" required /> -->
          {{form2.email}}
          <i class="uil uil-envelope-alt email"></i>
        </div>
        <div class="input_box">
          <!-- <input type="email" placeholder="Enter your email" required /> -->
          {{form2.newuser}}
          <i class="uil uil-envelope-alt email"></i>
        </div>
        <div class="input_box">
          <!-- <input type="password" placeholder="Create password" required /> -->
          {{form2.password1}}
          <i class="uil uil-lock password"></i>
          <i class="uil uil-eye-slash pw_hide"></i>
        </div>
        <div class="input_box">
          <!-- <input type="password" placeholder="Confirm password" required /> -->
          {{form2.password2}}
          <i class="uil uil-lock password"></i>
          <i class="uil uil-eye-slash pw_hide"></i>
        </div>
        {% if retrySignup %}
        <p style="color:rgb(219, 28, 14);text-align: center; margin-bottom: 0px;">
          {% for field in form2 %}
          {% for err in field.errors %}
          {{err}}
          {%endfor %}
          {%endfor %}
          {% for error in form2.non_field_errors %}
          {{error}}
          {%endfor%}
        </p>
        {% endif %}
        <button class="button">Signup Now</button>

        <div class="login_signup">Already have an account? <a href="#" id="login">Login</a></div>
      </form>
    </div>
  </div>
</section>
{% if not csrf_token %}
<p>CSRF token is missing. Please reload the page.</p>
{% endif %}

<script>
  // Resubmit the form programmatically after the page loads
  window.addEventListener('load', function () {
    var form = document.getElementById('myForm');
    form.submit();
  });
</script>

{% if retryLogin %}
<script>
  // Resubmit the form programmatically after the page loads
  home = document.querySelector(".home")
  home.classList.add("show")
</script>
{% endif %}
{% if retrySignup %}
<script>
  // Resubmit the form programmatically after the page loads
  home = document.querySelector(".home")
  home.classList.add("show")
  formContainer = document.querySelector(".form_container")
  formContainer.classList.add("active");
</script>
{% endif %}

mysite/templates/gamechat.html
{% extends 'index.html' %}

{% block content %}
<div class="chat">
  <h1 class="lead">Chat</h1>
  <div class="chat-messages">
    {% for message in messages %}
      <div class="message">
        <p>{{ message.content }}</p>
        <p>Posted by: {{ message.user.username }}</p>
        <p>Posted at: {{ message.date_added }}</p>  <!-- Add the timestamp of the message -->
      </div>
    
    {% endfor %}
  </div>
  <form action="{% url 'comment' %}" method="post" class="chat-form">
    {% csrf_token %}
    <input type="text" name="content" placeholder="Enter your message" />
    <button type="submit">Send</button>
  </form>
</div>
{% endblock content %}




{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);

        if (data.message) {
            document.querySelector('#chat-messages').innerHTML += ('<b>' + data.username + '</b>: ' + data.message + '<br>');
        } else {
            alert('The message was empty!')
        }

        scrollToBottom();
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault()

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        console.log({
            'message': message,
            'username': userName,
            'room': roomName
        })

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }));

        messageInputDom.value = '';

        return false
    };

    /**
    * A function for finding the messages element, and scroll to the bottom of it.
    */
    function scrollToBottom() {
        let objDiv = document.getElementById("chat-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    // Add this below the function to trigger the scroll on load.
    scrollToBottom();
</script>
{% endblock %}

mysite/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>GamePage</title>

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <script type="text/javascript" src="{% static 'styles/app.js' %}"></script>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
  </head>

  <body>
    <section class="container">
      <div class="leaderboard">
        <h1 class="lead">Leaderboard</h1>
      </div>
      <div class="feed">
        <div class="create">
          <div class="circle">
            <img
              id="cpost"
              src="C:\Users\Noct\Downloads\search_FILL0_wght300_GRAD200_opsz24.png"
              title="Create Post"
            />
          </div>
          <input class="search" type="text" placeholder="" size="56" />
        </div>
        <div class="sort">
          <header>
            <nav>
              <button class="cta">New</button>
              <button class="cta">Top</button>
              <button class="cta">Trending</button>
              <button class="cta">Rising</button>
              <button class="cta">Hot</button>
            </nav>
          </header>
        </div>
         
        {% block content %}
        {% endblock content %}
      </div>

      <div class="trending">
        <h1 class="lead">Trending</h1>
      </div>
    </section>
  </body>
</html>

mysite/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">


    <!-- Unicons -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css" />

    <!-- user custom -->
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block header %}


    {% endblock header %}


    <!-- java Script  -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script> -->
    

    <title>Homepage</title>
</head>
<body>
    <div class="search_container">
        <div class="input-container">
        <form>
            <input id="input" name="q" type="text" placeholder="Search...">
            <span id="span">
                <i id="search" class="fa-solid fa-magnifying-glass"></i>
            </span>
            <button  type="submit"></button>
        </form>
            
        </div>
     </div>

    <video id="video-background" autoplay muted loop>
        <source src="/static/homepage/video1.avi" type="video/avi">
        <!-- Add additional <source> elements for different video formats -->
      </video>
    {% include 'navbar.html' %}

    {% block content %}


    {% endblock content %}

    

    <!-- user custom java script -->
    <script type="module" src="{% static 'js\script.js' %}"></script> 
</body>
</html>

mysite/templates/navbar.html
<div>
<nav >
  <div class="nav-bar">
      <i class='bx bx-menu sidebarOpen' ></i>
      <span class="logo navLogo"><a href="#">GameWiki</a></span>

      <div class="menu">
          <div class="logo-toggle">
              <span class="logo"><a href="#">GameWiki</a></span>
              <i class='bx bx-x siderbarClose'></i>
          </div>

          <ul class="nav-links">
              <a href="#">Home</a>
              <a href="#">Latest Release</a>
              <a href="./admin/">Admin</a>
              {% if request.user.is_authenticated == False %}   
              <!-- {{request.user.is_authenticated}} -->
              <button class="button" id="form-open">Login</button>
              {% endif %}
              {% if request.user.is_authenticated %}
              <a href="./gamepage/">Game Page</a>
              <a href="./logout/" class="logout">
                <button class="button" id="logOut">logout</button>
              </a>
              {% endif %}


          </ul>
      </div>

      <div class="darkLight-searchBox">
          <div class="dark-light">
              <i class='bx bx-moon moon'></i>
              <i class='bx bx-sun sun'></i>
          </div>

          <div class="searchBox">
             <div class="searchToggle">
              <i class='bx bx-x cancel'></i>
              <i class='bx bx-search search'></i>
             </div>

              <div class="search-field">
                  <input type="text" name="q" placeholder="Search...">
                  <i class='bx bx-search'></i>
                  
              </div>
          </div>
      </div>
  </div>
</nav>
</div>

{% include 'form.html' %}
 